### ISSUE TITLE
error when execute analysis.R

### ISSUE THREAD

**Issue by santi-d** [toddwschneider/flim-springfield#3] opened 2016-10-21 20:43 UTC
Hi, when I run analysis.R script I get error by name, seems that don't recognize code: %>%, can you comment to me if it is correct because I don't know this commend.

Thanks.

**Comment by toddwschneider** [comment] 2016-10-23 12:51
@focker321 are you sure that you have installed all of the packages in `analysis.R`?

`%>%` is valid R code, but it requires that you load the external packages

**Comment by santi-d** [comment] 2016-10-23 18:19
Hi, yes I installed all packages:

 library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

```
filter, lag
```

The following objects are masked from ‘package:base’:

```
intersect, setdiff, setequal, union
```

> library(readr)
> library(ggplot2)
> library(scales)

Attaching package: ‘scales’

The following objects are masked from ‘package:readr’:

```
col_factor, col_numeric
```

> library(tidytext)
> library(lubridate)

Attaching package: ‘lubridate’

The following object is masked from ‘package:base’:

```
date
```

> library(stringr)
> library(extrafont)
> Registering fonts with R
> library(grid)
> library(gridExtra)

Attaching package: ‘gridExtra’

The following object is masked from ‘package:dplyr’:

```
combine
```

> library(RPostgreSQL)
> Loading required package: DBI
> source("helpers.R")
> query("
> -   SELECT
> -     c.id AS character_id,
> -     c.name,
> -     c.normalized_name,
> -     c.gender,
> -     SUM(s.word_count) AS word_count,
> -     COUNT(*) AS line_count,
> -     COUNT(DISTINCT episode_id) AS episode_count
> -   FROM characters c, script_lines s
> -   WHERE c.id = s.character_id
> -     AND s.speaking_line = true
> -     AND s.word_count > 0
> -   GROUP BY c.id
> -   ORDER BY SUM(s.word_count) DESC, c.normalized_name
> - ") %>% mutate(
> -   name = ifelse(is.na(name_mapping[name]), name, name_mapping[name]),
> -   name = factor(name, levels = rev(name)),
> -   gender = factor(gender, levels = c("f", "m"), labels = c("female", "male"))
> - )
>   Error in eval(substitute(expr), envir, enclos) : 
>   objeto 'name' no encontrado

**Comment by toddwschneider** [comment] 2016-10-23 22:15
@focker321 it looks like the problem is that the query returns no results

Are you sure that the Ruby code all ran properly? Can you confirm that there are records in your database's `characters` and `script_lines` tables?

**Comment by santi-d** [comment] 2016-10-23 22:16
When I run ruby code, I execute until set_gender, after this, no message is generated, 3 hours aprox.

**Comment by toddwschneider** [comment] 2016-10-30 13:27
Closing, see https://github.com/toddwschneider/flim-springfield/issues/2 for more info

**Closed as completed by toddwschneider** 2016-10-30 13:27 UTC
